name: Microsoft TTS
description: Text to speech using Microsoft Azure
version: 1.4.1
slug: wyoming_microsoft_tts
init: false
arch:
  - aarch64
  - amd64
discovery:
  - wyoming
ports:
  10200/tcp: null
options:
  debug_logging: false
  update_voices: true
schema:
  subscription_key: str
  service_region: str
  rate: str?
  pitch: str?
  volume: str?
  style: str?
  style_degree: str?
  debug_logging: bool
  update_voices: bool
tmpfs: true
image: ghcr.io/hugobloem/{arch}-wyoming-microsoft-tts
